service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - grafana-intern.norafith.ru

datasources:
  prometheus:
    enabled: true
    name: Prometheus
    type: prometheus
    url: http://prometheus-server:9090
    access: proxy
    isDefault: true
    editable: true
