alertmanager:
  enabled: true

server:
  global:
    scrape_interval: 15s
  service:
    type: NodePort
    port: 9090

nodeExporter:
  enabled: true
  service:
    port: 9100
  extraScrapeConfigs:
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter:9100']

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
