- name: Enable Minikube Ingress addon
  shell: minikube addons enable ingress
  args:
    creates: /root/.minikube/addons/ingress_enabled

- name: Wait for Ingress addon to initialize
  pause:
    seconds: 30

- name: Copy Ingress configuration
  copy:
    src: "{{ playbook_dir }}/roles/expose_ingress_controller/templates/ingress.yaml"
    dest: /home/{{ ansible_user }}/ingress.yaml

- name: Apply Ingress configuration
  shell: kubectl apply -f /home/{{ ansible_user }}/ingress.yaml
  args:
    executable: /bin/bash

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/server-info-app
    mode: '0644'

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/server-info-app
    dest: /etc/nginx/sites-enabled/server-info-app
    state: link

- name: Allow necessary ports through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'

- name: Enable UFW
  ufw:
    state: enabled

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Set up port forwarding for Ingress
  shell: kubectl port-forward service/ingress-nginx-controller -n ingress-nginx 80:80
  async: 300
  poll: 0